import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/customer/common/Navbar";
import Footer from "@/components/customer/common/Footer";
import ChatbotFloatingButton from "@/components/customer/common/ChatbotFloatingButton";
import { Providers } from "./providers";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Head>
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
            />
        </Head>
        <body
            className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
          min-h-screen
          flex flex-col
          bg-white
        `}
        >
        <Navbar />
        <Providers>
            <main className="flex-grow">{children}</main>
        </Providers>
        <Footer />
        <ChatbotFloatingButton />
        </body>
        </html>
    );
}
